In [1]:
# The following is from "big run"
import sys
sys.path.append('..')
from lib import *
import pandas as pd
import numpy as np

# Setup
lsa_np = np.load('../data/parsed/lsa_output.npy')
metadata = pd.read_pickle('../data/parsed/pickles/pickled_data_test.pickle')
metadata = metadata.loc[metadata['Scenario'] == '401']
metadata = metadata.reset_index(drop=True)
lsa_df = pd.DataFrame(lsa_np)
df = pd.concat([metadata, lsa_df], axis=1, join_axes=[metadata.index])
df = df.loc[df['Label'] != '-1']
df = df.reset_index(drop=True)
cat_features = ['To','From']
features = list(range(100))
features.extend(cat_features + ['Date'])
# features.extend(cat_features + ['ID'])

df = df[features + ['Label'] + ['ID']]
# df = df[features + ['ID']]

In [2]:
# TODO: test tree behavior in ml_master when given .2 of training set to work with
# TODO: rather than making each tree its own process, divide the number of trees by the number of cores, and create
#       a list of trees that can be processed linearly in its own core.s

num_trees = 64
tries = 1
num_increments = 999
random_seed = 600
random_seed = None
overall_training_ratio = .8
initial_training_ratio = .2
increment_size = 10
cross_val_rnf_incremental(num_trees, df, tries, num_increments, random_seed,cat_features, overall_training_ratio,
                          initial_training_ratio, increment_size)

too many increments specified (999), running with the max possible: (42)
LABELS:
['1', '1', '1', '0', '0', '1', '0', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '1', '0', '1', '0', '1', '0', '1', '1', '0', '1', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0', '1', '1', '1', '0', '1', '0', '0', '1', '1', '1', '1', '1', '0', '1', '1', '1', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '0', '0', '1', '0', '1', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '1', '1', '1', '0', '1', '0', '1', '1', '1', '1', '1', '0', '1', '0', '1', '1', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '1', '0', '0', '0', '1', '0']
predicted_classes:
['0', '1', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '1', '0', '1', '0', '1'

KeyError: 0

In [2]:
forest = RNF(df, 10, 100, 100, 11, 100, [])
forest.fit_parallel()

In [5]:
df["Label"][0]

'0'

In [ ]:
import time
start = time.time()
print(forest.predict(df[-100:], visualize=True))
end = time.time()
print(end - start)

In [ ]:
import time
start = time.time()
print(forest.predict(df[-100:], visualize=False))
end = time.time()
print(end - start)

In [18]:
import time
f1 = RNF(df, 64, 100, 1458, 11, 500, ["To", "From"])
f2 = RNF(df, 64, 100, 1458, 11, 500, ["To", "From"])

start = time.time()
f1.fit()
end = time.time()
print(end - start)

start = time.time()
f2.fit_parallel()
end = time.time()
print(end - start)

fitting the 1th tree.
fitting the 2th tree.
fitting the 3th tree.
when splitting categorically, no best address found: [393 237 435 456 237 393 242 455 327 352 330 388 269 254 439 456 458 308
 291 291 472 305 434 327 300 457 292 300 291 393 457 302 439]
fitting the 4th tree.
fitting the 5th tree.
when splitting categorically, no best address found: [147 252 433 267 489 489 252 551 551 288]
when splitting categorically, no best address found: [149 149 152]
fitting the 6th tree.
fitting the 7th tree.
fitting the 8th tree.
fitting the 9th tree.
fitting the 10th tree.
when splitting categorically, no best address found: [336 330 311 464 464 387 378 302 332 467 328 308 390 464 378 336 434 372
 311 393 347 305 354 311 448]
when splitting categorically, no best address found: [282 240 283 394 396 394 394 265 283 304]
when splitting categorically, no best address found: [267 309 249 274 432 551 433  87 432  87 535 487 535 552]
when splitting categorically, no best address found: [405 400 410 4

In [22]:
f2.predict(df[-10:])

([array([ 0.38120295,  0.61879705]),
  array([ 0.41273485,  0.58726515]),
  array([ 0.35487013,  0.64512987]),
  array([ 0.32808405,  0.67191595]),
  array([ 0.44346597,  0.55653403]),
  array([ 0.42146303,  0.57853697]),
  array([ 0.31431877,  0.68568123]),
  array([ 0.41273485,  0.58726515]),
  array([ 0.42146303,  0.57853697]),
  array([ 0.42146303,  0.57853697])],
 ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'])